### ISSUE TITLE
Unable to make install

### ISSUE THREAD

**Issue by GDPlayer** [morgant/mlvwmrc#13]
```
⋊> ~/mlvwmrc on master ◦ sudo make install                              07:14:24
mkdir -p /root/bin
install -b -B .`date +%Y%m%d-%H%M%S` -m 700 -o root bin/mlvwm-* /root/bin
install: invalid option -- 'B'
Try 'install --help' for more information.
make: *** [Makefile:72: install-bin] Error 1
```

**Comment by f-yildirim** [comment]
I've faced the same issue.
-B option is not supported by the current 'install' installation on my environment.
Edit the Makefile and remove   -B .`date +%Y%m%d-%H%M%S`  from the install line.

**Comment by morgant** [comment]
My apologies, @GDPlayer, and -- yes -- @f-yildirim is correct that I accidentally used a non-standard install(1) `-B` option. Good catch! I'll remove that.

**Comment by morgant** [comment]
Also, FYI, all files are installed into `$HOME`, so using `sudo`/`doas` should not be necessary. In fact, since it does download files from the Internet, I'd highly suggest _not running as root_.

**Comment by morgant** [comment]
@GDPlayer @f-yildirim I have updated `Makefile`'s 'install-bin' target to no longer use install(1) `-B` option and instead `find` & `mv` the target files in the destination to a timestamped backup.

I did something similar for the 'install' target to prevent overwriting customizations in `$HOME/.mlvwm/` to partially address Issue #8.
